server.port=8085
spring.application.name=payment-service

spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Vishu@5697
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=TourManagementSystemSecretKeyForJWTTokenGeneration2024SecureKey

razorpay.key-id=${RAZORPAY_KEY_ID:rzp_test_TKmAC2UpFqpQYP}
razorpay.key-secret=${RAZORPAY_KEY_SECRET:zfstXMiDj5Bf2yYOmbOxaj08}
service.booking.url=http://localhost:8084
service.package.url=http://localhost:8083
